<a href="https://colab.research.google.com/github/deenadayalandms/Maths-for-ML/blob/main/Intro_to_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Segment 1: Data Structures for Algebra**

##Scalars (Rank 0 Tensors) in Base Python

In [ ]:
x = 25

In [ ]:
type(x)

int

In [ ]:
y = 3

In [ ]:
sum = x + y
sum

28

In [ ]:
x_float= 25.0
float_sum = x_float + y
float_sum

28.0

In [ ]:
type(x_float)

float

Scalars in PyTorch

In [ ]:
import torch

In [ ]:
X_pt= torch.tensor(25)
X_pt

tensor(25)

In [ ]:
X_pt.shape

torch.Size([])

##Vectors (Rank 1 Tensors)

Vectors in NumPy

In [ ]:
import numpy as np

In [ ]:
x = np.array([25,2,5])  # type argument is optional, e.g.: dtype=np.float16
x

array([25,  2,  5])

In [ ]:
len(x)

3

In [ ]:
x.shape

(3,)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x[0]

25

In [ ]:
type(x[0])

numpy.int64

Vector Transposition

In [ ]:
x_t = x.T
x_t

array([25,  2,  5])

In [ ]:
y = np.array([[25, 2, 5]]) #doubt
y

array([[25,  2,  5]])

In [ ]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [ ]:
y_t.shape

(3, 1)

Zero vectors

In [ ]:
z = np.zeros(3)
z

array([0., 0., 0.])

Vectors in PyTorch

In [ ]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

##Norms and Units


L2 Norm

In [ ]:
(25**2 + 2**2 + 5**2 )**(1/2)

25.573423705088842

In [ ]:
np.linalg.norm(x)

25.573423705088842

L1 Norm

In [ ]:
np.abs(25) + np.abs(2) + np.abs(5)

32

Squared L^2 Norm

In [ ]:
(25**2)+(2**2)+(5**2)

654

In [ ]:
np.dot(x, x)

654

Max Norm

In [ ]:
np.max([np.abs(25), np.abs(2) , np.abs(5)])

25

Orthogonal Vectors


In [ ]:
i = np.array([1, 0])
i

array([1, 0])

In [ ]:
j = np.array([0, 1])
j

array([0, 1])

In [ ]:
np.dot(i, j)

0

## Matrices  (Rank 2 Tensors)

Matrices in Numpy

In [ ]:
# Use array() with nested brackets:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [ ]:
X.shape

(3, 2)

In [ ]:
X.size

6

In [ ]:
# Select left column of matrix X (zero-indexed)
X[:,0]

array([25,  5,  3])

In [ ]:
# Select middle row of matrix X:
X[1,:]

array([ 5, 26])

In [ ]:
# Another slicing-by-index example:
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

Matrices in PyTorch

In [ ]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [ ]:
X_pt.shape # more pythonic

torch.Size([3, 2])

In [ ]:
X_pt[1,:]

tensor([ 5, 26])

## Higher-Rank Tensors
As an example, rank 4 tensors are common for images, where each dimension corresponds to:

1.   Number of images in training batch, e.g., 32
2.   Image height in pixels, e.g., 28 for MNIST digits
3. Image width in pixels, e.g., 28
4. Number of color channels, e.g., 3 for full-color images (RGB)

In [ ]:
images_pt = torch.zeros([32, 28, 28, 3]) #PyTorch

In [ ]:
images_pt

#**Segment 2: Common Tensor Operations**

##Tensor Transposition

In [ ]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [ ]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [ ]:
X_pt.T #PyTorch

tensor([[25,  5,  3],
        [ 2, 26,  7]])

##Basic Tensor Arithmetic

In [ ]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [ ]:
X+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [ ]:
X*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [ ]:
X_pt*2+2 # Python operators are overloaded; could alternatively use torch.mul() or torch.add()

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [ ]:
torch.add(torch.mul(X_pt,2),2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])